import visita
import turno
import procedimiento
import tipo_procedimiento
import tipo_denuncia
import nacionalidad
import escolaridad
import ocupacion
import tipo_documento
import profesion
import estadocivil
import raza
import persona
import denuncia
import tipo_implicados
import tipo_delitos
import departamentos
import municipios

